// Must have humao.rest-client extension installed
// create .env in this directory with key:value pairings

GET https://{{$dotenv DEV_ENDPOINT}}drink-search/
?drink=blue

###
GET https://{{$dotenv DEV_ENDPOINT}}drink/
?drink=Belgian Blue

###
GET https://{{$dotenv DEV_ENDPOINT}}ingredient/
?ingredient=vodka